# Generated by Django 5.2 on 2025-04-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Published date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category'),
        ),
    ]
